.
├── list.txt
├── ops
│   ├── abs.py
│   ├── Activation.py
│   ├── adam_update.py
│   ├── add_n.py
│   ├── add.py
│   ├── all_finite.py
│   ├── arccosh.py
│   ├── arccos.py
│   ├── arcsinh.py
│   ├── arcsin.py
│   ├── arctanh.py
│   ├── arctan.py
│   ├── argmax_channel.py
│   ├── argmax.py
│   ├── argmin.py
│   ├── argsort.py
│   ├── AvgPool1D.py
│   ├── AvgPool2D.py
│   ├── batch_dot.py
│   ├── BatchNorm.py
│   ├── BilinearSampler.py
│   ├── BlockGrad.py
│   ├── broadcast_add.py
│   ├── broadcast_axes.py
│   ├── broadcast_div.py
│   ├── broadcast_equal.py
│   ├── broadcast_greater_equal.py
│   ├── broadcast_greater.py
│   ├── broadcast_hypot.py
│   ├── broadcast_lesser_equal.py
│   ├── broadcast_lesser.py
│   ├── broadcast_like.py
│   ├── broadcast_logical_and.py
│   ├── broadcast_logical_or.py
│   ├── broadcast_logical_xor.py
│   ├── broadcast_maximum.py
│   ├── broadcast_minimum.py
│   ├── broadcast_minus.py
│   ├── broadcast_mod.py
│   ├── broadcast_mul.py
│   ├── broadcast_not_equal.py
│   ├── broadcast_plus.py
│   ├── broadcast_power.py
│   ├── broadcast_sub.py
│   ├── broadcast_to.py
│   ├── cast_storage.py
│   ├── cbrt.py
│   ├── ceil.py
│   ├── clip.py
│   ├── col2im.py
│   ├── concat1.py
│   ├── concat.py
│   ├── Conv1D.py
│   ├── Conv1DTranspose.py
│   ├── Conv2D.py
│   ├── Conv2DTranspose.py
│   ├── Correlation.py
│   ├── cos.py
│   ├── CTCLoss.py
│   ├── cumsum.py
│   ├── Custom.py
│   ├── degrees.py
│   ├── depth_to_space.py
│   ├── diag.py
│   ├── dot.py
│   ├── Dropout.py
│   ├── elemwise_add.py
│   ├── elemwise_div.py
│   ├── elemwise_mul.py
│   ├── elemwise_sub.py
│   ├── Embedding.py
│   ├── erfinv.py
│   ├── erf.py
│   ├── expand_dims.py
│   ├── expm1.py
│   ├── exp.py
│   ├── fill_element_0index.py
│   ├── fix.py
│   ├── flatten.py
│   ├── Flatten.py
│   ├── flip.py
│   ├── floor.py
│   ├── ftml_update.py
│   ├── ftrl_update.py
│   ├── FullyConnected.py
│   ├── gammaln.py
│   ├── gamma.py
│   ├── gather_nd.py
│   ├── GlobalAvgPool1D.py
│   ├── GlobalAvgPool2D.py
│   ├── GlobalMaxPool1D.py
│   ├── GlobalMaxPool2D.py
│   ├── GlobalSumPool1D.py
│   ├── GlobalSumPool2D.py
│   ├── GridGenerator.py
│   ├── GroupNorm.py
│   ├── hard_sigmoid.py
│   ├── identity.py
│   ├── im2col.py
│   ├── InstanceNorm.py
│   ├── khatri_rao.py
│   ├── L2Normalization.py
│   ├── lamb_update_phase1.py
│   ├── lamb_update_phase2.py
│   ├── LayerNorm.py
│   ├── LeakyReLU.py
│   ├── linalg_det.py
│   ├── linalg_extractdiag.py
│   ├── linalg_extracttrian.py
│   ├── linalg_gelqf.py
│   ├── linalg_gemm2.py
│   ├── linalg_gemm.py
│   ├── linalg_inverse.py
│   ├── linalg_makediag.py
│   ├── linalg_maketrian.py
│   ├── linalg_potrf.py
│   ├── linalg_potri.py
│   ├── linalg_slogdet.py
│   ├── linalg_sumlogdiag.py
│   ├── linalg_syrk.py
│   ├── linalg_trmm.py
│   ├── linalg_trsm.py
│   ├── log10.py
│   ├── log1p.py
│   ├── log2.py
│   ├── logical_not.py
│   ├── log_softmax.py
│   ├── LRN.py
│   ├── make_loss.py
│   ├── MakeLoss.py
│   ├── max_axis.py
│   ├── MaxPool1D.py
│   ├── MaxPool2D.py
│   ├── max.py
│   ├── mean.py
│   ├── min_axis.py
│   ├── moments.py
│   ├── mp_sgd_mom_update.py
│   ├── mp_sgd_update.py
│   ├── multi_all_finite.py
│   ├── multi_lamb_update.py
│   ├── multi_lars.py
│   ├── multi_mp_lamb_update.py
│   ├── multi_mp_sgd_mom_update.py
│   ├── multi_mp_sgd_update.py
│   ├── multi_sgd_mom_update.py
│   ├── multi_sgd_update.py
│   ├── multi_sum.py
│   ├── multi_sum_sq.py
│   ├── nanprod.py
│   ├── nansum.py
│   ├── negative.py
│   ├── one_hot.py
│   ├── ones_like.py
│   ├── pad.py
│   ├── pick.py
│   ├── preloaded_multi_mp_sgd_mom_update.py
│   ├── preloaded_multi_sgd_mom_update.py
│   ├── preloaded_multi_sgd_update.py
│   ├── preload_multi_mp_sgd_mom_update.py
│   ├── preload_multi_sgd_mom_update.py
│   ├── preload_multi_sgd_update.py
│   ├── prod.py
│   ├── radians.py
│   ├── random_exponential.py
│   ├── random_gamma.py
│   ├── random_generalized_negative_binomial.py
│   ├── random_negative_binomial.py
│   ├── random_normal.py
│   ├── random_poisson.py
│   ├── random_randint.py
│   ├── random_uniform.py
│   ├── ravel_multi_index.py
│   ├── rcbrt.py
│   ├── reciprocal.py
│   ├── relu.py
│   ├── repeat.py
│   ├── reset_arrays.py
│   ├── reshape_like.py
│   ├── reshape.py
│   ├── rint.py
│   ├── rmspropalex_update.py
│   ├── rmsprop_update.py
│   ├── RNN.py
│   ├── ROIPooling.py
│   ├── round.py
│   ├── rsqrt.py
│   ├── sample_exponential.py
│   ├── sample_gamma.py
│   ├── sample_generalized_negative_binomial.py
│   ├── sample_multinomial.py
│   ├── sample_negative_binomial.py
│   ├── sample_normal.py
│   ├── sample_poisson.py
│   ├── sample_uniform.py
│   ├── scatter_nd.py
│   ├── SequenceLast.py
│   ├── sequence_mask.py
│   ├── SequenceMask.py
│   ├── SequenceReverse.py
│   ├── sgd_mom_update.py
│   ├── sgd_update.py
│   ├── shape_array.py
│   ├── shuffle.py
│   ├── sigmoid.py
│   ├── sign.py
│   ├── signsgd_update.py
│   ├── signum_update.py
│   ├── sinh.py
│   ├── sin.py
│   ├── size_array.py
│   ├── slice_axis.py
│   ├── slice_like.py
│   ├── slice.py
│   ├── smooth_l1.py
│   ├── SoftmaxActivation.py
│   ├── softmax_cross_entropy.py
│   ├── softmax.py
│   ├── Softmax.py
│   ├── softmin.py
│   ├── softsign.py
│   ├── sort.py
│   ├── space_to_depth.py
│   ├── SpatialTransformer.py
│   ├── split.py
│   ├── sqrt.py
│   ├── square.py
│   ├── squeeze.py
│   ├── stack.py
│   ├── stop_gradient.py
│   ├── sueeze.py
│   ├── sum_axis.py
│   ├── SumPool1D.py
│   ├── SumPool2D.py
│   ├── SumPoolD.py
│   ├── sum.py
│   ├── swapaxes.py
│   ├── take.py
│   ├── tanh.py
│   ├── tan.py
│   ├── tile.py
│   ├── topk.py
│   ├── transpose.py
│   ├── trunc.py
│   ├── unravel_index.py
│   ├── UpSampling.py
│   └── where.py
├── ops-old
│   ├── abs.py
│   ├── Activation.py
│   ├── adam_update.py
│   ├── add_n.py
│   ├── add.py
│   ├── all_finite.py
│   ├── arccosh.py
│   ├── arccos.py
│   ├── arcsinh.py
│   ├── arcsin.py
│   ├── arctanh.py
│   ├── arctan.py
│   ├── argmax_channel.py
│   ├── argmax.py
│   ├── argmin.py
│   ├── argsort.py
│   ├── AvgPool1D.py
│   ├── AvgPool2D.py
│   ├── batch_dot.py
│   ├── BatchNorm.py
│   ├── BilinearSampler.py
│   ├── BlockGrad.py
│   ├── broadcast_add.py
│   ├── broadcast_axes.py
│   ├── broadcast_div.py
│   ├── broadcast_equal.py
│   ├── broadcast_greater_equal.py
│   ├── broadcast_greater.py
│   ├── broadcast_hypot.py
│   ├── broadcast_lesser_equal.py
│   ├── broadcast_lesser.py
│   ├── broadcast_like.py
│   ├── broadcast_logical_and.py
│   ├── broadcast_logical_or.py
│   ├── broadcast_logical_xor.py
│   ├── broadcast_maximum.py
│   ├── broadcast_minimum.py
│   ├── broadcast_minus.py
│   ├── broadcast_mod.py
│   ├── broadcast_mul.py
│   ├── broadcast_not_equal.py
│   ├── broadcast_plus.py
│   ├── broadcast_power.py
│   ├── broadcast_sub.py
│   ├── broadcast_to.py
│   ├── cast_storage.py
│   ├── cbrt.py
│   ├── ceil.py
│   ├── clip.py
│   ├── col2im.py
│   ├── concat1.py
│   ├── concat.py
│   ├── Conv1D.py
│   ├── Conv1DTranspose.py
│   ├── Conv2D.py
│   ├── Conv2DTranspose.py
│   ├── Correlation.py
│   ├── cos.py
│   ├── CTCLoss.py
│   ├── cumsum.py
│   ├── Custom.py
│   ├── degrees.py
│   ├── depth_to_space.py
│   ├── diag.py
│   ├── dot.py
│   ├── Dropout.py
│   ├── elemwise_add.py
│   ├── elemwise_div.py
│   ├── elemwise_mul.py
│   ├── elemwise_sub.py
│   ├── Embedding.py
│   ├── erfinv.py
│   ├── erf.py
│   ├── expand_dims.py
│   ├── expm1.py
│   ├── exp.py
│   ├── fill_element_0index.py
│   ├── fix.py
│   ├── flatten.py
│   ├── Flatten.py
│   ├── flip.py
│   ├── floor.py
│   ├── F.py
│   ├── ftml_update.py
│   ├── ftrl_update.py
│   ├── FullyConnected.py
│   ├── gammaln.py
│   ├── gamma.py
│   ├── gather_nd.py
│   ├── GlobalAvgPool1D.py
│   ├── GlobalAvgPool2D.py
│   ├── GlobalMaxPool1D.py
│   ├── GlobalMaxPool2D.py
│   ├── GlobalSumPool1D.py
│   ├── GlobalSumPool2D.py
│   ├── GridGenerator.py
│   ├── GroupNorm.py
│   ├── hard_sigmoid.py
│   ├── identity.py
│   ├── im2col.py
│   ├── InstanceNorm.py
│   ├── khatri_rao.py
│   ├── L2Normalization.py
│   ├── lamb_update_phase1.py
│   ├── lamb_update_phase2.py
│   ├── LayerNorm.py
│   ├── LeakyReLU.py
│   ├── linalg_det.py
│   ├── linalg_extractdiag.py
│   ├── linalg_extracttrian.py
│   ├── linalg_gelqf.py
│   ├── linalg_gemm2.py
│   ├── linalg_gemm.py
│   ├── linalg_inverse.py
│   ├── linalg_makediag.py
│   ├── linalg_maketrian.py
│   ├── linalg_potrf.py
│   ├── linalg_potri.py
│   ├── linalg_slogdet.py
│   ├── linalg_sumlogdiag.py
│   ├── linalg_syrk.py
│   ├── linalg_trmm.py
│   ├── linalg_trsm.py
│   ├── log10.py
│   ├── log1p.py
│   ├── log2.py
│   ├── logical_not.py
│   ├── log_softmax.py
│   ├── LRN.py
│   ├── make_loss.py
│   ├── MakeLoss.py
│   ├── max_axis.py
│   ├── MaxPool1D.py
│   ├── MaxPool2D.py
│   ├── max.py
│   ├── mean.py
│   ├── min_axis.py
│   ├── moments.py
│   ├── mp_sgd_mom_update.py
│   ├── mp_sgd_update.py
│   ├── multi_all_finite.py
│   ├── multi_lamb_update.py
│   ├── multi_lars.py
│   ├── multi_mp_lamb_update.py
│   ├── multi_mp_sgd_mom_update.py
│   ├── multi_mp_sgd_update.py
│   ├── multi_sgd_mom_update.py
│   ├── multi_sgd_update.py
│   ├── multi_sum.py
│   ├── multi_sum_sq.py
│   ├── nanprod.py
│   ├── nansum.py
│   ├── negative.py
│   ├── one_hot.py
│   ├── ones_like.py
│   ├── pad.py
│   ├── pick.py
│   ├── preloaded_multi_mp_sgd_mom_update.py
│   ├── preloaded_multi_sgd_mom_update.py
│   ├── preloaded_multi_sgd_update.py
│   ├── prod.py
│   ├── radians.py
│   ├── random_exponential.py
│   ├── random_gamma.py
│   ├── random_generalized_negative_binomial.py
│   ├── random_negative_binomial.py
│   ├── random_normal.py
│   ├── random_poisson.py
│   ├── random_randint.py
│   ├── random_uniform.py
│   ├── ravel_multi_index.py
│   ├── rcbrt.py
│   ├── reciprocal.py
│   ├── relu.py
│   ├── repeat.py
│   ├── reset_arrays.py
│   ├── reshape_like.py
│   ├── reshape.py
│   ├── rint.py
│   ├── rmspropalex_update.py
│   ├── rmsprop_update.py
│   ├── RNN.py
│   ├── ROIPooling.py
│   ├── round.py
│   ├── rsqrt.py
│   ├── sample_exponential.py
│   ├── sample_gamma.py
│   ├── sample_generalized_negative_binomial.py
│   ├── sample_multinomial.py
│   ├── sample_negative_binomial.py
│   ├── sample_normal.py
│   ├── sample_poisson.py
│   ├── sample_uniform.py
│   ├── scatter_nd.py
│   ├── SequenceLast.py
│   ├── sequence_mask.py
│   ├── SequenceMask.py
│   ├── SequenceReverse.py
│   ├── sgd_mom_update.py
│   ├── sgd_update.py
│   ├── shape_array.py
│   ├── shuffle.py
│   ├── sigmoid.py
│   ├── sign.py
│   ├── signsgd_update.py
│   ├── signum_update.py
│   ├── sinh.py
│   ├── sin.py
│   ├── size_array.py
│   ├── slice_axis.py
│   ├── slice_like.py
│   ├── slice.py
│   ├── smooth_l1.py
│   ├── SoftmaxActivation.py
│   ├── softmax_cross_entropy.py
│   ├── softmax.py
│   ├── Softmax.py
│   ├── softmin.py
│   ├── softsign.py
│   ├── sort.py
│   ├── space_to_depth.py
│   ├── SpatialTransformer.py
│   ├── split.py
│   ├── sqrt.py
│   ├── square.py
│   ├── squeeze.py
│   ├── stack.py
│   ├── stop_gradient.py
│   ├── sueeze.py
│   ├── sum_axis.py
│   ├── SumPool1D.py
│   ├── SumPool2D.py
│   ├── SumPoolD.py
│   ├── sum.py
│   ├── swapaxes.py
│   ├── take.py
│   ├── tanh.py
│   ├── tan.py
│   ├── tile.py
│   ├── topk.py
│   ├── transpose.py
│   ├── trunc.py
│   ├── unravel_index.py
│   ├── UpSampling.py
│   └── where.py
├── res
│   ├── abs.py_error.log
│   ├── abs.py_output.log
│   ├── abs.py_perf.log
│   ├── Activation.py_error.log
│   ├── Activation.py_output.log
│   ├── Activation.py_perf.log
│   ├── adam_update.py_error.log
│   ├── adam_update.py_output.log
│   ├── adam_update.py_perf.log
│   ├── add_n.py_error.log
│   ├── add_n.py_output.log
│   ├── add_n.py_perf.log
│   ├── add.py_error.log
│   ├── add.py_output.log
│   ├── add.py_perf.log
│   ├── all_finite.py_error.log
│   ├── all_finite.py_output.log
│   ├── all_finite.py_perf.log
│   ├── arccosh.py_error.log
│   ├── arccosh.py_output.log
│   ├── arccosh.py_perf.log
│   ├── arccos.py_error.log
│   ├── arccos.py_output.log
│   ├── arccos.py_perf.log
│   ├── arcsinh.py_error.log
│   ├── arcsinh.py_output.log
│   ├── arcsinh.py_perf.log
│   ├── arcsin.py_error.log
│   ├── arcsin.py_output.log
│   ├── arcsin.py_perf.log
│   ├── arctanh.py_error.log
│   ├── arctanh.py_output.log
│   ├── arctanh.py_perf.log
│   ├── arctan.py_error.log
│   ├── arctan.py_output.log
│   ├── arctan.py_perf.log
│   ├── argmax_channel.py_error.log
│   ├── argmax_channel.py_output.log
│   ├── argmax_channel.py_perf.log
│   ├── argmax.py_error.log
│   ├── argmax.py_output.log
│   ├── argmax.py_perf.log
│   ├── argmin.py_error.log
│   ├── argmin.py_output.log
│   ├── argmin.py_perf.log
│   ├── argsort.py_error.log
│   ├── argsort.py_output.log
│   ├── argsort.py_perf.log
│   ├── AvgPool1D.py_error.log
│   ├── AvgPool1D.py_output.log
│   ├── AvgPool1D.py_perf.log
│   ├── AvgPool2D.py_error.log
│   ├── AvgPool2D.py_output.log
│   ├── AvgPool2D.py_perf.log
│   ├── batch_dot.py_error.log
│   ├── batch_dot.py_output.log
│   ├── batch_dot.py_perf.log
│   ├── BatchNorm.py_error.log
│   ├── BatchNorm.py_output.log
│   ├── BatchNorm.py_perf.log
│   ├── BilinearSampler.py_error.log
│   ├── BilinearSampler.py_output.log
│   ├── BilinearSampler.py_perf.log
│   ├── BlockGrad.py_error.log
│   ├── BlockGrad.py_output.log
│   ├── BlockGrad.py_perf.log
│   ├── broadcast_add.py_error.log
│   ├── broadcast_add.py_output.log
│   ├── broadcast_add.py_perf.log
│   ├── broadcast_axes.py_error.log
│   ├── broadcast_axes.py_output.log
│   ├── broadcast_axes.py_perf.log
│   ├── broadcast_div.py_error.log
│   ├── broadcast_div.py_output.log
│   ├── broadcast_div.py_perf.log
│   ├── broadcast_equal.py_error.log
│   ├── broadcast_equal.py_output.log
│   ├── broadcast_equal.py_perf.log
│   ├── broadcast_greater_equal.py_error.log
│   ├── broadcast_greater_equal.py_output.log
│   ├── broadcast_greater_equal.py_perf.log
│   ├── broadcast_greater.py_error.log
│   ├── broadcast_greater.py_output.log
│   ├── broadcast_greater.py_perf.log
│   ├── broadcast_hypot.py_error.log
│   ├── broadcast_hypot.py_output.log
│   ├── broadcast_hypot.py_perf.log
│   ├── broadcast_lesser_equal.py_error.log
│   ├── broadcast_lesser_equal.py_output.log
│   ├── broadcast_lesser_equal.py_perf.log
│   ├── broadcast_lesser.py_error.log
│   ├── broadcast_lesser.py_output.log
│   ├── broadcast_lesser.py_perf.log
│   ├── broadcast_like.py_error.log
│   ├── broadcast_like.py_output.log
│   ├── broadcast_like.py_perf.log
│   ├── broadcast_logical_and.py_error.log
│   ├── broadcast_logical_and.py_output.log
│   ├── broadcast_logical_and.py_perf.log
│   ├── broadcast_logical_or.py_error.log
│   ├── broadcast_logical_or.py_output.log
│   ├── broadcast_logical_or.py_perf.log
│   ├── broadcast_logical_xor.py_error.log
│   ├── broadcast_logical_xor.py_output.log
│   ├── broadcast_logical_xor.py_perf.log
│   ├── broadcast_maximum.py_error.log
│   ├── broadcast_maximum.py_output.log
│   ├── broadcast_maximum.py_perf.log
│   ├── broadcast_minimum.py_error.log
│   ├── broadcast_minimum.py_output.log
│   ├── broadcast_minimum.py_perf.log
│   ├── broadcast_minus.py_error.log
│   ├── broadcast_minus.py_output.log
│   ├── broadcast_minus.py_perf.log
│   ├── broadcast_mod.py_error.log
│   ├── broadcast_mod.py_output.log
│   ├── broadcast_mod.py_perf.log
│   ├── broadcast_mul.py_error.log
│   ├── broadcast_mul.py_output.log
│   ├── broadcast_mul.py_perf.log
│   ├── broadcast_not_equal.py_error.log
│   ├── broadcast_not_equal.py_output.log
│   ├── broadcast_not_equal.py_perf.log
│   ├── broadcast_plus.py_error.log
│   ├── broadcast_plus.py_output.log
│   ├── broadcast_plus.py_perf.log
│   ├── broadcast_power.py_error.log
│   ├── broadcast_power.py_output.log
│   ├── broadcast_power.py_perf.log
│   ├── broadcast_sub.py_error.log
│   ├── broadcast_sub.py_output.log
│   ├── broadcast_sub.py_perf.log
│   ├── broadcast_to.py_error.log
│   ├── broadcast_to.py_output.log
│   ├── broadcast_to.py_perf.log
│   ├── cast_storage.py_error.log
│   ├── cast_storage.py_output.log
│   ├── cast_storage.py_perf.log
│   ├── cbrt.py_error.log
│   ├── cbrt.py_output.log
│   ├── cbrt.py_perf.log
│   ├── ceil.py_error.log
│   ├── ceil.py_output.log
│   ├── ceil.py_perf.log
│   ├── clip.py_error.log
│   ├── clip.py_output.log
│   ├── clip.py_perf.log
│   ├── col2im.py_error.log
│   ├── col2im.py_output.log
│   ├── col2im.py_perf.log
│   ├── concat1.py_error.log
│   ├── concat1.py_output.log
│   ├── concat1.py_perf.log
│   ├── concat.py_error.log
│   ├── concat.py_output.log
│   ├── concat.py_perf.log
│   ├── Conv1D.py_error.log
│   ├── Conv1D.py_output.log
│   ├── Conv1D.py_perf.log
│   ├── Conv1DTranspose.py_error.log
│   ├── Conv1DTranspose.py_output.log
│   ├── Conv1DTranspose.py_perf.log
│   ├── Conv2D.py_error.log
│   ├── Conv2D.py_output.log
│   ├── Conv2D.py_perf.log
│   ├── Conv2DTranspose.py_error.log
│   ├── Conv2DTranspose.py_output.log
│   ├── Conv2DTranspose.py_perf.log
│   ├── Correlation.py_error.log
│   ├── Correlation.py_output.log
│   ├── Correlation.py_perf.log
│   ├── cos.py_error.log
│   ├── cos.py_output.log
│   ├── cos.py_perf.log
│   ├── CTCLoss.py_error.log
│   ├── CTCLoss.py_output.log
│   ├── CTCLoss.py_perf.log
│   ├── cumsum.py_error.log
│   ├── cumsum.py_output.log
│   ├── cumsum.py_perf.log
│   ├── Custom.py_error.log
│   ├── Custom.py_output.log
│   ├── Custom.py_perf.log
│   ├── degrees.py_error.log
│   ├── degrees.py_output.log
│   ├── degrees.py_perf.log
│   ├── depth_to_space.py_error.log
│   ├── depth_to_space.py_output.log
│   ├── depth_to_space.py_perf.log
│   ├── diag.py_error.log
│   ├── diag.py_output.log
│   ├── diag.py_perf.log
│   ├── dot.py_error.log
│   ├── dot.py_output.log
│   ├── dot.py_perf.log
│   ├── Dropout.py_error.log
│   ├── Dropout.py_output.log
│   ├── Dropout.py_perf.log
│   ├── elemwise_add.py_error.log
│   ├── elemwise_add.py_output.log
│   ├── elemwise_add.py_perf.log
│   ├── elemwise_div.py_error.log
│   ├── elemwise_div.py_output.log
│   ├── elemwise_div.py_perf.log
│   ├── elemwise_mul.py_error.log
│   ├── elemwise_mul.py_output.log
│   ├── elemwise_mul.py_perf.log
│   ├── elemwise_sub.py_error.log
│   ├── elemwise_sub.py_output.log
│   ├── elemwise_sub.py_perf.log
│   ├── Embedding.py_error.log
│   ├── Embedding.py_output.log
│   ├── Embedding.py_perf.log
│   ├── erfinv.py_error.log
│   ├── erfinv.py_output.log
│   ├── erfinv.py_perf.log
│   ├── erf.py_error.log
│   ├── erf.py_output.log
│   ├── erf.py_perf.log
│   ├── expand_dims.py_error.log
│   ├── expand_dims.py_output.log
│   ├── expand_dims.py_perf.log
│   ├── expm1.py_error.log
│   ├── expm1.py_output.log
│   ├── expm1.py_perf.log
│   ├── exp.py_error.log
│   ├── exp.py_output.log
│   ├── exp.py_perf.log
│   ├── fill_element_0index.py_error.log
│   ├── fill_element_0index.py_output.log
│   ├── fill_element_0index.py_perf.log
│   ├── fix.py_error.log
│   ├── fix.py_output.log
│   ├── fix.py_perf.log
│   ├── flatten.py_error.log
│   ├── Flatten.py_error.log
│   ├── flatten.py_output.log
│   ├── Flatten.py_output.log
│   ├── flatten.py_perf.log
│   ├── Flatten.py_perf.log
│   ├── flip.py_error.log
│   ├── flip.py_output.log
│   ├── flip.py_perf.log
│   ├── floor.py_error.log
│   ├── floor.py_output.log
│   ├── floor.py_perf.log
│   ├── F.py_error.log
│   ├── F.py_output.log
│   ├── F.py_perf.log
│   ├── ftml_update.py_error.log
│   ├── ftml_update.py_output.log
│   ├── ftml_update.py_perf.log
│   ├── ftrl_update.py_error.log
│   ├── ftrl_update.py_output.log
│   ├── ftrl_update.py_perf.log
│   ├── FullyConnected.py_error.log
│   ├── FullyConnected.py_output.log
│   ├── FullyConnected.py_perf.log
│   ├── gammaln.py_error.log
│   ├── gammaln.py_output.log
│   ├── gammaln.py_perf.log
│   ├── gamma.py_error.log
│   ├── gamma.py_output.log
│   ├── gamma.py_perf.log
│   ├── gather_nd.py_error.log
│   ├── gather_nd.py_output.log
│   ├── gather_nd.py_perf.log
│   ├── GlobalAvgPool1D.py_error.log
│   ├── GlobalAvgPool1D.py_output.log
│   ├── GlobalAvgPool1D.py_perf.log
│   ├── GlobalAvgPool2D.py_error.log
│   ├── GlobalAvgPool2D.py_output.log
│   ├── GlobalAvgPool2D.py_perf.log
│   ├── GlobalMaxPool1D.py_error.log
│   ├── GlobalMaxPool1D.py_output.log
│   ├── GlobalMaxPool1D.py_perf.log
│   ├── GlobalMaxPool2D.py_error.log
│   ├── GlobalMaxPool2D.py_output.log
│   ├── GlobalMaxPool2D.py_perf.log
│   ├── GlobalSumPool1D.py_error.log
│   ├── GlobalSumPool1D.py_output.log
│   ├── GlobalSumPool1D.py_perf.log
│   ├── GlobalSumPool2D.py_error.log
│   ├── GlobalSumPool2D.py_output.log
│   ├── GlobalSumPool2D.py_perf.log
│   ├── GridGenerator.py_error.log
│   ├── GridGenerator.py_output.log
│   ├── GridGenerator.py_perf.log
│   ├── GroupNorm.py_error.log
│   ├── GroupNorm.py_output.log
│   ├── GroupNorm.py_perf.log
│   ├── hard_sigmoid.py_error.log
│   ├── hard_sigmoid.py_output.log
│   ├── hard_sigmoid.py_perf.log
│   ├── identity.py_error.log
│   ├── identity.py_output.log
│   ├── identity.py_perf.log
│   ├── im2col.py_error.log
│   ├── im2col.py_output.log
│   ├── im2col.py_perf.log
│   ├── InstanceNorm.py_error.log
│   ├── InstanceNorm.py_output.log
│   ├── InstanceNorm.py_perf.log
│   ├── khatri_rao.py_error.log
│   ├── khatri_rao.py_output.log
│   ├── khatri_rao.py_perf.log
│   ├── L2Normalization.py_error.log
│   ├── L2Normalization.py_output.log
│   ├── L2Normalization.py_perf.log
│   ├── lamb_update_phase1.py_error.log
│   ├── lamb_update_phase1.py_output.log
│   ├── lamb_update_phase1.py_perf.log
│   ├── lamb_update_phase2.py_error.log
│   ├── lamb_update_phase2.py_output.log
│   ├── lamb_update_phase2.py_perf.log
│   ├── LayerNorm.py_error.log
│   ├── LayerNorm.py_output.log
│   ├── LayerNorm.py_perf.log
│   ├── LeakyReLU.py_error.log
│   ├── LeakyReLU.py_output.log
│   ├── LeakyReLU.py_perf.log
│   ├── linalg_det.py_error.log
│   ├── linalg_det.py_output.log
│   ├── linalg_det.py_perf.log
│   ├── linalg_extractdiag.py_error.log
│   ├── linalg_extractdiag.py_output.log
│   ├── linalg_extractdiag.py_perf.log
│   ├── linalg_extracttrian.py_error.log
│   ├── linalg_extracttrian.py_output.log
│   ├── linalg_extracttrian.py_perf.log
│   ├── linalg_gelqf.py_error.log
│   ├── linalg_gelqf.py_output.log
│   ├── linalg_gelqf.py_perf.log
│   ├── linalg_gemm2.py_error.log
│   ├── linalg_gemm2.py_output.log
│   ├── linalg_gemm2.py_perf.log
│   ├── linalg_gemm.py_error.log
│   ├── linalg_gemm.py_output.log
│   ├── linalg_gemm.py_perf.log
│   ├── linalg_inverse.py_error.log
│   ├── linalg_inverse.py_output.log
│   ├── linalg_inverse.py_perf.log
│   ├── linalg_makediag.py_error.log
│   ├── linalg_makediag.py_output.log
│   ├── linalg_makediag.py_perf.log
│   ├── linalg_maketrian.py_error.log
│   ├── linalg_maketrian.py_output.log
│   ├── linalg_maketrian.py_perf.log
│   ├── linalg_potrf.py_error.log
│   ├── linalg_potrf.py_output.log
│   ├── linalg_potrf.py_perf.log
│   ├── linalg_potri.py_error.log
│   ├── linalg_potri.py_output.log
│   ├── linalg_potri.py_perf.log
│   ├── linalg_slogdet.py_error.log
│   ├── linalg_slogdet.py_output.log
│   ├── linalg_slogdet.py_perf.log
│   ├── linalg_sumlogdiag.py_error.log
│   ├── linalg_sumlogdiag.py_output.log
│   ├── linalg_sumlogdiag.py_perf.log
│   ├── linalg_syrk.py_error.log
│   ├── linalg_syrk.py_output.log
│   ├── linalg_syrk.py_perf.log
│   ├── linalg_trmm.py_error.log
│   ├── linalg_trmm.py_output.log
│   ├── linalg_trmm.py_perf.log
│   ├── linalg_trsm.py_error.log
│   ├── linalg_trsm.py_output.log
│   ├── linalg_trsm.py_perf.log
│   ├── log10.py_error.log
│   ├── log10.py_output.log
│   ├── log10.py_perf.log
│   ├── log1p.py_error.log
│   ├── log1p.py_output.log
│   ├── log1p.py_perf.log
│   ├── log2.py_error.log
│   ├── log2.py_output.log
│   ├── log2.py_perf.log
│   ├── logical_not.py_error.log
│   ├── logical_not.py_output.log
│   ├── logical_not.py_perf.log
│   ├── log_softmax.py_error.log
│   ├── log_softmax.py_output.log
│   ├── log_softmax.py_perf.log
│   ├── LRN.py_error.log
│   ├── LRN.py_output.log
│   ├── LRN.py_perf.log
│   ├── make_loss.py_error.log
│   ├── MakeLoss.py_error.log
│   ├── make_loss.py_output.log
│   ├── MakeLoss.py_output.log
│   ├── make_loss.py_perf.log
│   ├── MakeLoss.py_perf.log
│   ├── max_axis.py_error.log
│   ├── max_axis.py_output.log
│   ├── max_axis.py_perf.log
│   ├── MaxPool1D.py_error.log
│   ├── MaxPool1D.py_output.log
│   ├── MaxPool1D.py_perf.log
│   ├── MaxPool2D.py_error.log
│   ├── MaxPool2D.py_output.log
│   ├── MaxPool2D.py_perf.log
│   ├── max.py_error.log
│   ├── max.py_output.log
│   ├── max.py_perf.log
│   ├── mean.py_error.log
│   ├── mean.py_output.log
│   ├── mean.py_perf.log
│   ├── min_axis.py_error.log
│   ├── min_axis.py_output.log
│   ├── min_axis.py_perf.log
│   ├── moments.py_error.log
│   ├── moments.py_output.log
│   ├── moments.py_perf.log
│   ├── mp_sgd_mom_update.py_error.log
│   ├── mp_sgd_mom_update.py_output.log
│   ├── mp_sgd_mom_update.py_perf.log
│   ├── mp_sgd_update.py_error.log
│   ├── mp_sgd_update.py_output.log
│   ├── mp_sgd_update.py_perf.log
│   ├── multi_all_finite.py_error.log
│   ├── multi_all_finite.py_output.log
│   ├── multi_all_finite.py_perf.log
│   ├── multi_lamb_update.py_error.log
│   ├── multi_lamb_update.py_output.log
│   ├── multi_lamb_update.py_perf.log
│   ├── multi_lars.py_error.log
│   ├── multi_lars.py_output.log
│   ├── multi_lars.py_perf.log
│   ├── multi_mp_lamb_update.py_error.log
│   ├── multi_mp_lamb_update.py_output.log
│   ├── multi_mp_lamb_update.py_perf.log
│   ├── multi_mp_sgd_mom_update.py_error.log
│   ├── multi_mp_sgd_mom_update.py_output.log
│   ├── multi_mp_sgd_mom_update.py_perf.log
│   ├── multi_mp_sgd_update.py_error.log
│   ├── multi_mp_sgd_update.py_output.log
│   ├── multi_mp_sgd_update.py_perf.log
│   ├── multi_sgd_mom_update.py_error.log
│   ├── multi_sgd_mom_update.py_output.log
│   ├── multi_sgd_mom_update.py_perf.log
│   ├── multi_sgd_update.py_error.log
│   ├── multi_sgd_update.py_output.log
│   ├── multi_sgd_update.py_perf.log
│   ├── multi_sum.py_error.log
│   ├── multi_sum.py_output.log
│   ├── multi_sum.py_perf.log
│   ├── multi_sum_sq.py_error.log
│   ├── multi_sum_sq.py_output.log
│   ├── multi_sum_sq.py_perf.log
│   ├── mxnet_operator_benchmark_results.json
│   ├── nanprod.py_error.log
│   ├── nanprod.py_output.log
│   ├── nanprod.py_perf.log
│   ├── nansum.py_error.log
│   ├── nansum.py_output.log
│   ├── nansum.py_perf.log
│   ├── negative.py_error.log
│   ├── negative.py_output.log
│   ├── negative.py_perf.log
│   ├── one_hot.py_error.log
│   ├── one_hot.py_output.log
│   ├── one_hot.py_perf.log
│   ├── ones_like.py_error.log
│   ├── ones_like.py_output.log
│   ├── ones_like.py_perf.log
│   ├── pad.py_error.log
│   ├── pad.py_output.log
│   ├── pad.py_perf.log
│   ├── perf_data.log
│   ├── pick.json
│   ├── pick.py_error.log
│   ├── pick.py_output.log
│   ├── pick.py_perf.log
│   ├── preloaded_multi_mp_sgd_mom_update.py_error.log
│   ├── preloaded_multi_mp_sgd_mom_update.py_output.log
│   ├── preloaded_multi_mp_sgd_mom_update.py_perf.log
│   ├── preloaded_multi_sgd_mom_update.py_error.log
│   ├── preloaded_multi_sgd_mom_update.py_output.log
│   ├── preloaded_multi_sgd_mom_update.py_perf.log
│   ├── preloaded_multi_sgd_update.py_error.log
│   ├── preloaded_multi_sgd_update.py_output.log
│   ├── preloaded_multi_sgd_update.py_perf.log
│   ├── prod.py_error.log
│   ├── prod.py_output.log
│   ├── prod.py_perf.log
│   ├── profile.json
│   ├── radians.py_error.log
│   ├── radians.py_output.log
│   ├── radians.py_perf.log
│   ├── random_exponential.py_error.log
│   ├── random_exponential.py_output.log
│   ├── random_exponential.py_perf.log
│   ├── random_gamma.py_error.log
│   ├── random_gamma.py_output.log
│   ├── random_gamma.py_perf.log
│   ├── random_generalized_negative_binomial.py_error.log
│   ├── random_generalized_negative_binomial.py_output.log
│   ├── random_generalized_negative_binomial.py_perf.log
│   ├── random_negative_binomial.py_error.log
│   ├── random_negative_binomial.py_output.log
│   ├── random_negative_binomial.py_perf.log
│   ├── random_normal.py_error.log
│   ├── random_normal.py_output.log
│   ├── random_normal.py_perf.log
│   ├── random_poisson.py_error.log
│   ├── random_poisson.py_output.log
│   ├── random_poisson.py_perf.log
│   ├── random_randint.py_error.log
│   ├── random_randint.py_output.log
│   ├── random_randint.py_perf.log
│   ├── random_uniform.py_error.log
│   ├── random_uniform.py_output.log
│   ├── random_uniform.py_perf.log
│   ├── ravel_multi_index.py_error.log
│   ├── ravel_multi_index.py_output.log
│   ├── ravel_multi_index.py_perf.log
│   ├── rcbrt.py_error.log
│   ├── rcbrt.py_output.log
│   ├── rcbrt.py_perf.log
│   ├── reciprocal.py_error.log
│   ├── reciprocal.py_output.log
│   ├── reciprocal.py_perf.log
│   ├── relu.py_error.log
│   ├── relu.py_output.log
│   ├── relu.py_perf.log
│   ├── repeat.py_error.log
│   ├── repeat.py_output.log
│   ├── repeat.py_perf.log
│   ├── reset_arrays.py_error.log
│   ├── reset_arrays.py_output.log
│   ├── reset_arrays.py_perf.log
│   ├── reshape_like.py_error.log
│   ├── reshape_like.py_output.log
│   ├── reshape_like.py_perf.log
│   ├── reshape.py_error.log
│   ├── reshape.py_output.log
│   ├── reshape.py_perf.log
│   ├── rint.py_error.log
│   ├── rint.py_output.log
│   ├── rint.py_perf.log
│   ├── rmspropalex_update.py_error.log
│   ├── rmspropalex_update.py_output.log
│   ├── rmspropalex_update.py_perf.log
│   ├── rmsprop_update.py_error.log
│   ├── rmsprop_update.py_output.log
│   ├── rmsprop_update.py_perf.log
│   ├── RNN.py_error.log
│   ├── RNN.py_output.log
│   ├── RNN.py_perf.log
│   ├── ROIPooling.py_error.log
│   ├── ROIPooling.py_output.log
│   ├── ROIPooling.py_perf.log
│   ├── round.py_error.log
│   ├── round.py_output.log
│   ├── round.py_perf.log
│   ├── rsqrt.py_error.log
│   ├── rsqrt.py_output.log
│   ├── rsqrt.py_perf.log
│   ├── sample_exponential.py_error.log
│   ├── sample_exponential.py_output.log
│   ├── sample_exponential.py_perf.log
│   ├── sample_gamma.py_error.log
│   ├── sample_gamma.py_output.log
│   ├── sample_gamma.py_perf.log
│   ├── sample_generalized_negative_binomial.py_error.log
│   ├── sample_generalized_negative_binomial.py_output.log
│   ├── sample_generalized_negative_binomial.py_perf.log
│   ├── sample_multinomial.py_error.log
│   ├── sample_multinomial.py_output.log
│   ├── sample_multinomial.py_perf.log
│   ├── sample_negative_binomial.py_error.log
│   ├── sample_negative_binomial.py_output.log
│   ├── sample_negative_binomial.py_perf.log
│   ├── sample_normal.py_error.log
│   ├── sample_normal.py_output.log
│   ├── sample_normal.py_perf.log
│   ├── sample_poisson.py_error.log
│   ├── sample_poisson.py_output.log
│   ├── sample_poisson.py_perf.log
│   ├── sample_uniform.py_error.log
│   ├── sample_uniform.py_output.log
│   ├── sample_uniform.py_perf.log
│   ├── scatter_nd.py_error.log
│   ├── scatter_nd.py_output.log
│   ├── scatter_nd.py_perf.log
│   ├── SequenceLast.py_error.log
│   ├── SequenceLast.py_output.log
│   ├── SequenceLast.py_perf.log
│   ├── sequence_mask.py_error.log
│   ├── SequenceMask.py_error.log
│   ├── sequence_mask.py_output.log
│   ├── SequenceMask.py_output.log
│   ├── sequence_mask.py_perf.log
│   ├── SequenceMask.py_perf.log
│   ├── SequenceReverse.py_error.log
│   ├── SequenceReverse.py_output.log
│   ├── SequenceReverse.py_perf.log
│   ├── sgd_mom_update.py_error.log
│   ├── sgd_mom_update.py_output.log
│   ├── sgd_mom_update.py_perf.log
│   ├── sgd_update.py_error.log
│   ├── sgd_update.py_output.log
│   ├── sgd_update.py_perf.log
│   ├── shape_array.py_error.log
│   ├── shape_array.py_output.log
│   ├── shape_array.py_perf.log
│   ├── shuffle.py_error.log
│   ├── shuffle.py_output.log
│   ├── shuffle.py_perf.log
│   ├── sigmoid.py_error.log
│   ├── sigmoid.py_output.log
│   ├── sigmoid.py_perf.log
│   ├── sign.py_error.log
│   ├── sign.py_output.log
│   ├── sign.py_perf.log
│   ├── signsgd_update.py_error.log
│   ├── signsgd_update.py_output.log
│   ├── signsgd_update.py_perf.log
│   ├── signum_update.py_error.log
│   ├── signum_update.py_output.log
│   ├── signum_update.py_perf.log
│   ├── sinh.py_error.log
│   ├── sinh.py_output.log
│   ├── sinh.py_perf.log
│   ├── sin.py_error.log
│   ├── sin.py_output.log
│   ├── sin.py_perf.log
│   ├── size_array.py_error.log
│   ├── size_array.py_output.log
│   ├── size_array.py_perf.log
│   ├── slice_axis.py_error.log
│   ├── slice_axis.py_output.log
│   ├── slice_axis.py_perf.log
│   ├── slice_like.py_error.log
│   ├── slice_like.py_output.log
│   ├── slice_like.py_perf.log
│   ├── slice.py_error.log
│   ├── slice.py_output.log
│   ├── slice.py_perf.log
│   ├── smooth_l1.py_error.log
│   ├── smooth_l1.py_output.log
│   ├── smooth_l1.py_perf.log
│   ├── SoftmaxActivation.py_error.log
│   ├── SoftmaxActivation.py_output.log
│   ├── SoftmaxActivation.py_perf.log
│   ├── softmax_cross_entropy.py_error.log
│   ├── softmax_cross_entropy.py_output.log
│   ├── softmax_cross_entropy.py_perf.log
│   ├── softmax.py_error.log
│   ├── Softmax.py_error.log
│   ├── softmax.py_output.log
│   ├── Softmax.py_output.log
│   ├── softmax.py_perf.log
│   ├── Softmax.py_perf.log
│   ├── softmin.py_error.log
│   ├── softmin.py_output.log
│   ├── softmin.py_perf.log
│   ├── softsign.py_error.log
│   ├── softsign.py_output.log
│   ├── softsign.py_perf.log
│   ├── sort.py_error.log
│   ├── sort.py_output.log
│   ├── sort.py_perf.log
│   ├── space_to_depth.py_error.log
│   ├── space_to_depth.py_output.log
│   ├── space_to_depth.py_perf.log
│   ├── SpatialTransformer.py_error.log
│   ├── SpatialTransformer.py_output.log
│   ├── SpatialTransformer.py_perf.log
│   ├── split.py_error.log
│   ├── split.py_output.log
│   ├── split.py_perf.log
│   ├── sqrt.py_error.log
│   ├── sqrt.py_output.log
│   ├── sqrt.py_perf.log
│   ├── square.py_error.log
│   ├── square.py_output.log
│   ├── square.py_perf.log
│   ├── squeeze.py_error.log
│   ├── squeeze.py_output.log
│   ├── squeeze.py_perf.log
│   ├── stack.py_error.log
│   ├── stack.py_output.log
│   ├── stack.py_perf.log
│   ├── stop_gradient.py_error.log
│   ├── stop_gradient.py_output.log
│   ├── stop_gradient.py_perf.log
│   ├── sueeze.py_error.log
│   ├── sueeze.py_output.log
│   ├── sueeze.py_perf.log
│   ├── sum_axis.py_error.log
│   ├── sum_axis.py_output.log
│   ├── sum_axis.py_perf.log
│   ├── SumPool1D.py_error.log
│   ├── SumPool1D.py_output.log
│   ├── SumPool1D.py_perf.log
│   ├── SumPool2D.py_error.log
│   ├── SumPool2D.py_output.log
│   ├── SumPool2D.py_perf.log
│   ├── SumPoolD.py_error.log
│   ├── SumPoolD.py_output.log
│   ├── SumPoolD.py_perf.log
│   ├── sum.py_error.log
│   ├── sum.py_output.log
│   ├── sum.py_perf.log
│   ├── swapaxes.py_error.log
│   ├── swapaxes.py_output.log
│   ├── swapaxes.py_perf.log
│   ├── take.py_error.log
│   ├── take.py_output.log
│   ├── take.py_perf.log
│   ├── tanh.py_error.log
│   ├── tanh.py_output.log
│   ├── tanh.py_perf.log
│   ├── tan.py_error.log
│   ├── tan.py_output.log
│   ├── tan.py_perf.log
│   ├── tile.py_error.log
│   ├── tile.py_output.log
│   ├── tile.py_perf.log
│   ├── topk.py_error.log
│   ├── topk.py_output.log
│   ├── topk.py_perf.log
│   ├── transpose.py_error.log
│   ├── transpose.py_output.log
│   ├── transpose.py_perf.log
│   ├── trunc.py_error.log
│   ├── trunc.py_output.log
│   ├── trunc.py_perf.log
│   ├── unravel_index.py_error.log
│   ├── unravel_index.py_output.log
│   ├── unravel_index.py_perf.log
│   ├── UpSampling.py_error.log
│   ├── UpSampling.py_output.log
│   ├── UpSampling.py_perf.log
│   ├── where.py_error.log
│   ├── where.py_output.log
│   └── where.py_perf.log
├── test2.sh
└── utils_patch.patch

4 directories, 1234 files
